In [1]:
import numpy as np

import matplotlib as plt

import time

# Check Numpy version
print(f"Numpy version: {np.__version__}")

# Display settings for cleaner output
np.set_printoptions(precision=3, suppress=True)


Numpy version: 2.3.3


#### **Understanding Numpy**


- Numpy (Numerical Python) is the foundation library for scientific computing in python. it provides powerful N-dimensional array object and tools for working with these arrays.

- We import NumPy with the standard alias `np`. The print options make arrays display more readably by limiting decimal places and avoiding scientific notation for numbers like 0.001

**Numpy Data Structure**

- Numpy arrays are fundamentally from pythons lists:
  - Homogenous: All elements must be the same data type
    Fixed size: Size is determined at creation (though you can create new arrays )
- Memory efficient: Elements stored in contiguous memory blocks
- Vectorizeed operations: Mathematical operations work on entire arrays

In [2]:
#Creating arrays from python lists 
# 1D array: A simple sequence of numbers 
arr1d = np.array([1,2,3,4,5])

# 2D array: Think of this as a matrix or table with rows and columns
arr2d = np.array([[1,2,3],
                  [4,5,6]])
# 3D array: like a stack of 2D arrays - useful for images, time series, etc.
arr3d = np.array([[[1, 2], [3, 4]],
                 [[5, 6], [7, 8]]])

print("1D array:", arr1d)
print("2D array:\n", arr2d)
print("3D array:\n", arr3d)

1D array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]
3D array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


When you pass a nested list to `np.array()`, Numpy automatically determines the dimensions. The 1D array is like a single row, 2D is like a spreadsheeet, and 3D is like multiple spreadsheets stacked together 

In [17]:
# Creating arrays filled with zeros - useful for initializing arrays 
# Shape (3, 4) means 3 rows and 4 columns
zeros = np.zeros((3, 4))

# Creating arrays filled with ones - often used as starting points
ones = np.ones((2, 3, 4))     #3D array: 2layers, 3 rows, 4 columns

#Empty array - faster than zeros/ones but contains random values 
#Use when ypu nwill immediately fill array with real data
empty = np.empty((2, 2))

print("Zeros array (3x4):\n", zeros)
print('Ones arrays shape:', ones.shape)
print("Empty array (contains random values):\n", empty)

Zeros array (3x4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones arrays shape: (2, 3, 4)
Empty array (contains random values):
 [[0.25 0.5 ]
 [0.75 1.  ]]


`zeros` and `ones` are memory-efficient ways to create arrays of specific sizes. `empty()` is fastest but contains garbage values, so onlyb use it when you'll immediately overwrite the contents. 

In [22]:
# Range arrays - like Pythons range() but more powerful
range_arr = np.arange(0, 10, 2) #start, stop, step : [0, 2, 4, 6, 8]
print("Range array:", range_arr)

# Linearly spaced arrays - divide a r4ange into equal parts 
# From 0 to 1 with exactly 5 points (including endpoints)
linespace_arr = np.linspace(0, 2, 5)
print("Linspace array:", linespace_arr)

# Logarithmically spaced arrays - useful for scientific data
# From 10^0 to 10^2 (1 to 100) with 5 points
logspace_arr = np.logspace(0, 2, 5)
print("Logspace array:", logspace_arr)

Range array: [0 2 4 6 8]
Linspace array: [0.  0.5 1.  1.5 2. ]
Logspace array: [  1.      3.162  10.     31.623 100.   ]


- `arange()` works like Python's range() but returns a Numpy array and works with floats.
- `arange()` divides a range into equal segmentsn - useful for plotting smooth curves.
- `logspace()` creates points that are evenly spaced on a logarithmic scale.

In [21]:
#Identity matrix - diagonal of ones, zeros elsewhere

# Essential for linear algebra operations
identity = np.eye(4)    # 4x4 identity matrix

# Diagonal matrix - put values on the diagonal
diagonal = np.diag([1,2,3,4])

#Array7 filled with a specfic value
full_arr = np.full((3,3), 7)     # 3x3 array filled with 7

print("Identity matrix:\n", identity)
print("Diagonal matrix:\n", diagonal)
print("Full array (filled with 7):\n", full_arr)



Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Diagonal matrix:
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
Full array (filled with 7):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


Identity matrices are crucial in linear algebra - multiplying any matrix by an identity matrix returns the original matrix. Diagonal matrices are useful for scaling operations

**Numpy Data Types (dtypes)**
- Understanding data types is crucial for memeory efficiency and numerical precision.

In [5]:
#Explicit data types is crucial memory usage and preccision
int_arr = np.array([1, 2, 3], dtype=np.int32)  #32-bit integers
float_arr = np.array([1.2,3], dtype=np.float64) # 64-bits floats (double precision)
bool_arr = np.array([True, False, True], dtype=np.bool_)  #boolean values

#Types conversion -change memory usage and precision
converted = int_arr.astype(np.float32)  #convert to 32-bit float

print("Integer array dtype:", int_arr.dtype)
print("float array dtype:", float_arr.dtype)
print("Boolean array dtype:", bool_arr.dtype)
print('Converted array dtype:', converted .dtype)

#Memory usage comparison 
print(f"int32 uses {int_arr.itemsize} bytes per element")
print(f"float64 uses {float_arr.itemsize} bytes per element")

Integer array dtype: int32
float array dtype: float64
Boolean array dtype: bool
Converted array dtype: float32
int32 uses 4 bytes per element
float64 uses 8 bytes per element
