Name: Osho Ridwanullah Ayomide
Track: AI Engineering


Class Task 2


Given the following matrices:

``B = [[1, 2], 
     [- 2, 0], 
     [5, - 3]] ``
     
``A = [[2, - 1, 3],
    [0, 4, 1]]``

a Identify the number of rows and columns in each matrix.
b Determine whether the matrices can be multiplied. If so, specify whether it's (AB), (BA), or both.
If the multiplication is defined, compute the resulting matrix.

``Solution:``

 a. Matrix B has 2 rows and 3 columns
    Matrix A has 3 rows and 2 columns

 b. Yes, the matrix can be multiplied. Matrix (BA) and (AB) can be multiplied.

 c. B x A =
  ``B = [[1, 2], 
     [- 2, 0], 
     [5, - 3]] ``  `` x ``  ``A = [[2, - 1, 3],
    [0, 4, 1]]``

    = [[2,7,5],[-4, 2 ,-6],[10, -17, 12]]



    A x B =   A = [[2, - 1, 3],[0, 4, 1]]  X  B = [[1, 2], 
     [- 2, 0], 
     [5, - 3]] 

     = [[19, -5], [-3, -3]]
     
    


In [1]:
import numpy as np 

In [2]:
A = np.array([[2, - 1, 3],[0, 4, 1]])
B = np.array([[1, 2],[- 2, 0],[5, - 3]] )

print(np.matmul(A,B))
print(np.matmul(B,A))

[[19 -5]
 [-3 -3]]
[[  2   7   5]
 [ -4   2  -6]
 [ 10 -17  12]]
