##Linear Algebra##

**Class Task 3**

**Name: Osho Ridwanullah Ayomide**

**Track: AI ENGINEERING**

# 3.1 Represent the scores as a 4x3 matrix
let A = 
\begin{bmatrix}
80 & 70 & 90 \\ 
60 & 85 & 75 \\ 
95 & 88 & 92 \\ 
70 & 60 & 65
\end{bmatrix}

# 3.2 Compute the total score for each students by summing acrosss the row vector 

Summing the matrix row-wise to get the total score for each students we have 

*student 1 = 80 + 70 + 90 = 240*

*student 2 = 60 + 85 + 75 = 220*

*student 3 = 95 + 88 + 92 = 275*

*student 4 = 70 + 60 + 65 = 195*

\begin{bmatrix}
student & Total Score \\
Student1 & 240 \\
Student2 & 220 \\
Student3 & 275 \\
Student4 & 195
\end{bmatrix}


# 3.3 Applying weights (Scalar Multiplication)
Mathematics obviously weighs x2 of the other courses so we are considering it.
We will be picking the first column.

\begin{bmatrix}
80 \\ 60 \\ 95 \\ 70
\end{bmatrix} × 2 = 

\begin{bmatrix}
160 \\ 120 \\ 190 \\ 140
\end{bmatrix}



# 3.4 Calculate the average mean 

Avg_mean_subject 1 = (80 + 60 + 95 + 70)  / 4 = 76.25

Avg_mean_subject 2 = (70 + 85 + 88 + 60) / 4 = 75.75

Avg_mean_subject 3 = (90 + 75 + 92 +65) / 4 = 80.5


\begin{bmatrix}
subject & Mean \\
Subject 1 & 76.25 \\
Subject 2 & 75.75 \\
Subject 3 & 80.5 \\
\end{bmatrix}

# 3.5 Final Grades Using Matrix Multiplication

using the weight vector= 

\begin{bmatrix}
0.5 \\ 0.3 \\ 0.2
\end{bmatrix}

multiplied by the student scores

student score = 

\begin{bmatrix}
80 & 70 & 90 \\ 
60 & 85 & 75 \\ 
95 & 88 & 92 \\ 
70 & 60 & 65
\end{bmatrix}

final grades = 

\begin{bmatrix}
79 \\ 70.5 \\ 92.3 \\ 66
\end{bmatrix}

# 3.6 Comparing Students (Vector Subtraction)

lets compare student 1 and student 2

\begin{bmatrix}
Student 1 & 80 & 70 & 90 \\ 
Student 2 & 60 & 85 & 75
\end{bmatrix}

subtracting their score vectors we have

[20, -15, 25]




In [3]:
import numpy as np

In [4]:
# 3.1 Represent the scores as a 4x3 matrix

A= np.array([[80, 70, 90], [60, 85, 75], [95, 88, 92], [70, 60, 65]])
A

array([[80, 70, 90],
       [60, 85, 75],
       [95, 88, 92],
       [70, 60, 65]])

In [5]:
# 3.2 Total score for each student

print('the total score for each student:', np.sum(A, axis= 1))

the total score for each student: [240 220 275 195]


In [6]:
# 3.3 Applying weights (Scalar Multiplication)

c = 2
Math_col = np.array([[80],[60],[95],[70]])

scalar_mult = c * Math_col

print(f'Weights = \n {scalar_mult}')

Weights = 
 [[160]
 [120]
 [190]
 [140]]


In [7]:
# 3.4 Calculate the average mean 

print('Average mean = ', np.mean(A, axis=0))

Average mean =  [76.25 75.75 80.5 ]


In [8]:
#3.5 Final Grades Using Matrix Multiplication

Weight_vector = np.array([[0.5],[0.3],[0.2]])

A= np.array([[80, 70, 90], 
             [60, 85, 75], 
             [95, 88, 92], 
             [70, 60, 65]])

#Multiplying the matrix A by the weight

MatriX_Mul = A @ Weight_vector
MatriX_Mul

array([[79. ],
       [70.5],
       [92.3],
       [66. ]])

In [9]:
# 3.6 Comparing Students (Vector Subtraction)

# lets compare student 1 and student 2

student_1 = np.array([80, 70, 90])
student_2 = np.array([60, 85, 75])

Vector_subtraction = student_1 - student_2
Vector_subtraction

array([ 20, -15,  15])