In [2]:
import numpy as np

In [4]:
# 3.1 Represent the scores as a 4x3 matrix

A= np.array([[80, 70, 90], [60, 85, 75], [95, 88, 92], [70, 60, 65]])
A

array([[80, 70, 90],
       [60, 85, 75],
       [95, 88, 92],
       [70, 60, 65]])

In [5]:
# 3.2 Total score for each student

print('the total score for each student:', np.sum(A, axis= 1))

the total score for each student: [240 220 275 195]


In [7]:
# 3.3 Applying weights (Scalar Multiplication)

c = 2
Math_col = np.array([[80],[60],[95],[70]])

scalar_mult = c * Math_col

print(f'Weights = \n {scalar_mult}')

Weights = 
 [[160]
 [120]
 [190]
 [140]]


In [8]:
# 3.4 Calculate the average mean 

print('Average mean = ', np.mean(A, axis=0))

Average mean =  [76.25 75.75 80.5 ]


In [ ]:
# 3.5 Final Grades Using Matrix Multiplication

Weight_vector = np.array([[0.5],[0.3],[0.2]])

A= np.array([[80, 70, 90], 
             [60, 85, 75], 
             [95, 88, 92], 
             [70, 60, 65]])

#Multiplying the matrix A by the weight

MatriX_Mul = A @ Weight_vector
MatriX_Mul

array([[79. ],
       [70.5],
       [92.3],
       [66. ]])

In [13]:
# 3.6 Comparing Students (Vector Subtraction)

# lets compare student 1 and student 2

student_1 = np.array([80, 70, 90])
student_2 = np.array([60, 85, 75])

Vector_subtraction = student_1 - student_2
Vector_subtraction

array([ 20, -15,  15])