**Linear Algebra**

In [1]:
import numpy as np

In [7]:
#Compute the following
A = np.array([[2,-1],[0,3]])
B = np.array([[1,4],[-2,5]])

c=2
d= 3

cA = c*A
print(cA)

dB = d*B
print(dB)

v1 = (c + d)*A
print(v1)

[[ 4 -2]
 [ 0  6]]
[[ 3 12]
 [-6 15]]
[[10 -5]
 [ 0 15]]


In [ ]:
# (B)

#Scalar Multiplication

#Associative property: (c.d)A = C.(dA)

v5 = (c*d)*A
print(v5)

v6 = c*(d*A)
print(v6)

print(f"Associative:", {np.array_equal(v5,v6)})


[[12 -6]
 [ 0 18]]
[[12 -6]
 [ 0 18]]
distributive: {True}


In [ ]:
#Distributive property: c(A + B) = cA + cB

v7= c*(A + B)
print(v7)

v8 = c*A + c*B
print(v8)

print(f"distributive:", {np.array_equal(v7,v8)})



[[ 6  6]
 [-4 16]]
[[ 6  6]
 [-4 16]]


In [14]:
#Scalar Addition; (c+d)A = A(c+d)
v9 = (c + d)*A
print(v9)

v10 = A*(c + d)
print(v10)

print(f"Scalar Addition:", {np.array_equal(v9,v10)})


[[10 -5]
 [ 0 15]]
[[10 -5]
 [ 0 15]]
Scalar Addition: {True}


In [15]:
#Transpose of A and B

A = np.array([[2,-1],[0,3]])

B = np.array([[1,4],[-2,5]])

print("\nTranspose A^T:")
print(A.T)
print("\nInverse A^(-1):")
print(np.linalg.inv(A))
print("\nDeterminant |A|:")
print(np.linalg.det(A))


Transpose A^T:
[[ 2  0]
 [-1  3]]

Inverse A^(-1):
[[0.5        0.16666667]
 [0.         0.33333333]]

Determinant |A|:
6.0


In [16]:
print("\nTranspose B^T:")
print(B.T)
print("\nInverse B^(-1):")
print(np.linalg.inv(B))
print("\nDeterminant |B|:")
print(np.linalg.det(B))


Transpose B^T:
[[ 1 -2]
 [ 4  5]]

Inverse B^(-1):
[[ 0.38461538 -0.30769231]
 [ 0.15384615  0.07692308]]

Determinant |B|:
13.0
