**Question 1**

- Create a 6x6 Numpy array


In [1]:
import numpy as np

In [6]:
arr = np.random.randint(1,50,[6,6])
print(arr)

[[42 25 10 11 12 27]
 [ 7 29  4 41 18 36]
 [30 13 49 49 11 34]
 [40 22 33 16 14 20]
 [ 2 27 20 14 42 10]
 [15 22 15 14 44 33]]


**Question 2**
- Extract the first two rows and the last three columns

In [ ]:
#The first two rows
print(arr[0:2])

[[42 25 10 11 12 27]
 [ 7 29  4 41 18 36]]


In [11]:
#The last three columns
print(arr[:, 3:])

[[11 12 27]
 [41 18 36]
 [49 11 34]
 [16 14 20]
 [14 42 10]
 [14 44 33]]


In [14]:
# All the even numbers in the array
even_num = (arr % 2 == 0)
print(arr[even_num])

[42 10 12  4 18 36 30 34 40 22 16 14 20  2 20 14 42 10 22 14 44]


**Question 3**
- Perform array transformation

In [15]:
reshape = arr.reshape(3,2,6)
print(reshape)

[[[42 25 10 11 12 27]
  [ 7 29  4 41 18 36]]

 [[30 13 49 49 11 34]
  [40 22 33 16 14 20]]

 [[ 2 27 20 14 42 10]
  [15 22 15 14 44 33]]]


- flattening

In [16]:
# Flatten the reshaped array back to 1D

flattened = reshape.flatten()
print(flattened)

[42 25 10 11 12 27  7 29  4 41 18 36 30 13 49 49 11 34 40 22 33 16 14 20
  2 27 20 14 42 10 15 22 15 14 44 33]


**Question 4**
- Generate a 4x4 matrix and replace the diagonals with numbers from 10 to 40 with a step of 10.

In [29]:
identity = np.eye(4)
diagonal_arr = np.arange(10,50,10)
np.fill_diagonal(identity, diagonal_arr)
print(identity)


[[10.  0.  0.  0.]
 [ 0. 20.  0.  0.]
 [ 0.  0. 30.  0.]
 [ 0.  0.  0. 40.]]


**Question 5**
- Perform a matrix multiplication between a 3x4 matrix of random integers(1-10)

In [26]:
arr1 = np.random.randint(1,10,[3,4])
arr2 = np.random.randint(1,10,[4,3])
flAT = arr2.flatten()
reshape = flAT.reshape(3,4)
print(arr1)
print(arr2)
print(arr1 * reshape)

[[3 2 1 7]
 [3 5 7 5]
 [8 4 3 6]]
[[6 5 4]
 [6 3 8]
 [4 7 8]
 [9 8 9]]
[[18 10  4 42]
 [ 9 40 28 35]
 [64 36 24 54]]


**Question 6**
- Create a function that takes a 2d NumPy array as input and returns a new array where: All even numbers are squared. 


In [1]:
def array_op():
    x = int(input("Enter number of rows: "))
    y = int(input("Enter number of columns: "))
    arr = []
    for i in range(x):
        for j in range(y):
            arr.append(int(input(f'value at row {i} and columnn {j}')))
    array = np.array(arr).reshape(x,y)

    square_arr = np.where(array % 2 == 0, array ** 2, array)
    odd_arr = np.where(square_arr %2 != 0, -1, square_arr)
    return(odd_arr)
array_op()

ValueError: invalid literal for int() with base 10: ''